### ISSUE TITLE
Wallet crash on Mac while starting up

### ISSUE THREAD

**Issue by FelixMendoza** [PWRcoin/PWRcoinClassic#29]
Hi there, my wallet started displaying a message that read Unable to Sync and it suddenly crashed. Now, every time I try to open the Wallet, it never opens. It automatically crashes during start-up while the "Loading Block Index..." message is displayed on the splash screen. I'm running version 3.1.0. of the waller and version 10.14.5 on my Mac Mini.
Any suggestions for me? Thanks!

**Comment by ghobson2013** [comment]
Hi,
Can you goto /Users/[YourMacUserName]/Library/Application Support/pwrcoin3 directory
and upload the db.log and debug.log you see in there.. make sure to compress it first if its big.

The blockchain db is likely corrupt , usually due to bad blocks on the disk, you may want to check
the health of your drive with "Disk Utility". You can reset the wallet , in other words make it re-download the entire blockchain by deleting all files in your /Users/[YourMacUserName]/Library/Application Support/pwrcoin3 directory except for "wallet.dat" and peers.dat.
Before you reset let me first look at the logs so upload those first.

Thanks

**Comment by FelixMendoza** [comment]
[Archive.zip](https://github.com/PWRcoin/PWRcoin/files/3324599/Archive.zip)
Hi thank you for getting back to me. Please see both docs compressed here.

**Comment by ghobson2013** [comment]
It looks like the wallet is finding a corrupt file on start up.
Can you delete Application Support/pwrcoin3/database/log.0000000015  and try to start the wallet.
If this fails you will have to clear out the pwrcoin3 directory except for wallet.dat and peers.dat and let the wallet resync from the beginning.  I hope you have made backups of wallet.dat.

Also show me the output of the command    ulimit -n
Thanks.

**Comment by PWRcoin** [comment]
Have you made progress on this issue Felix ?

**Comment by FelixMendoza** [comment]
Yes, thank you very much. The wallet is up and running again!

**Comment by PWRcoin** [comment]
very good, closing this issue.
